# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt update -y
    init: sudo apt install maven mysql-server -y
    command: mysql && CREATE DATABASE notes; && exit && mvn spring-boot:run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
