# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt update -y && sudo apt-get upgrade -f
    init: sudo apt-get install maven && sudo apt-get install mysql-server
    command: sudo mysql_secure_installation && sudo service mysql start && mysql -u root -p root@123 && "CREATE DATABASE notes;" && "exit;" && mvn spring-boot:run


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
