# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sudo apt install maven mysql-server
    command: sudo systemctl start mysql.service
    command: mysql -u root -p 9845003308rR@
    command: CREATE DATABASE notes;
    command: exit
    command: mvn spring-boot:run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
