# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt update -y && sudo apt-get upgrade -fy
    init: sudo apt-get install maven -y && sudo apt-get install mysql-server -y && sudo service mysql start && sudo mysql
    command: "CREATE DATABASE notes;" && "exit;" && mvn spring-boot:run


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
