# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt update -y && sudo apt-get upgrade -fy
    init: sudo apt-get install maven -y && sudo apt-get install mysql-server -y 
    command: sudo service mysql start && sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password by 'root@123';" && sudo mysql -e "create database notes;"  mvn spring-boot:run


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
