# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt update -y && docker network create notes-mysql
    init: sudo apt-get install maven -y && docker run --name mysql --network notes-mysql MYSQL_DATABASE=bootdb -e MYSQL_ROOT_PASSWORD= -d mysql
    command: mvn spring-boot:run


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
